### ISSUE TITLE
能正常使用了么？

### ISSUE THREAD

**Issue by CoderTonyChan** [sauvignon1989/Alibili#3]
还在拉TVVLCKit 很慢

**Comment by CoderTonyChan** [comment]
现在是API不允许还是VLC问题呢？ 弹幕正常 视频都加载不出来 url能获取 但是播放不了

**Comment by bemyae** [comment]
@CoderTonyChan 我好久没看这个project了不好意思,应该能用，本周回家看看（~2019.11.3）。如果不能用的话 我会更新库和 debug

**Comment by bemyae** [comment]
对比各种库之后，TVVLCKit是我pull的时候感觉最快的 所以才选这个的

**Comment by CoderTonyChan** [comment]
> @CoderTonyChan 我好久没看这个project了不好意思,应该能用，本周回家看看（~2019.11.3）。如果不能用的话 我会更新库和 debug

我一个视频都没加载到出来 TVVLCKit能支持修改http的头么？

**Comment by bemyae** [comment]
@CoderTonyChan 
不知道修改http的头具体指什么。https://github.com/sauvignon1989/Alibili/blob/d96adc71e060a32a431af67cb511be165799e065/Alibili/VideoPlayViewController.swift#L130
这行是读取 json中的视频的url,下面的132行读取声音，然后同部播放。当前版本运行不了的话，我周末会看看。
https://github.com/sauvignon1989/Alibili/blob/d96adc71e060a32a431af67cb511be165799e065/Alibili/VideoPlayViewController.swift#L132

**Comment by CoderTonyChan** [comment]
> @CoderTonyChan
> 不知道修改http的头具体指什么。
> 
> https://github.com/sauvignon1989/Alibili/blob/d96adc71e060a32a431af67cb511be165799e065/Alibili/VideoPlayViewController.swift#L130
> 
> 
> 这行是读取 json中的视频的url,下面的132行读取声音，然后同部播放。当前版本运行不了的话，我周末会看看。
> https://github.com/sauvignon1989/Alibili/blob/d96adc71e060a32a431af67cb511be165799e065/Alibili/VideoPlayViewController.swift#L132

获取URL是没有问题的 但是类似 http://upos-hz-mirrorks3u.acgvideo.com/upgcxcode/94/21/123912194/123912194_nb2-1-30080.m4s?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M=&uipk=5&nbs=1&deadline=1571310602&gen=playurl&os=ks3u&oi=249389971&trid=620a7ee4fe8743ecabae3085df94a0cdu&platform=pc&upsig=937373ea5d6e608afaa98a2b917dd7ce&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,platform&mid=520843 这种URL播放不了

**Comment by bemyae** [comment]
明白你的问题了.分两步回答 .
1. 能使用版本都是目前最新，在我家的AppleTV上可以跑看b站
2. url的播放 ，下面刚刚打出的连接是可以看的。你分享的连接我用浏览器都打不开 403，视频本身权限问题？或者说一定时间后权限消失？总之是可以播放的的。 （http://upos-hz-mirrorakam.akamaized.net/upgcxcode/96/45/126334596/126334596-1-30080.m4s?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M=&uipk=5&nbs=1&deadline=1572363833&gen=playurl&os=akam&oi=3064717349&trid=340192122135499bb6046ee292202873u&platform=pc&upsig=f48b2c05369d842ca83d79fea416859d&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,platform&hdnts=exp=1572363833~hmac=6eb365c62a42f67031d34b7b0e5c4f83a20d4175f0c607e27da5a15857aa4a16&mid=1299005）

**Comment by CoderTonyChan** [comment]
奇怪了 我编译的应该也是最新版本 扫码也正常登录 但是接口获取回来的链接我一个也播放不了
难道因为我跑在模拟器上？实机不方便拿回公司跑😂

**Comment by bemyae** [comment]
模拟器也是可以的😭
<img width="1279" alt="Screen Shot 2019-10-31 at 9 27 22" src="https://user-images.githubusercontent.com/27460257/67908960-c8a41580-fbc0-11e9-866a-cb2acb12d5bf.png">
