### ISSUE TITLE
m4s格式的视频无法播放

### ISSUE THREAD

**Issue by gongqingfeng** [sauvignon1989/Alibili#4]
作者你好，我下载了你的代码跑了一下，弹幕能够正常显示，但是视频和音频没有，我print了视频和音频的连接，是正常获取的。我测试了一下mp4格式的连接，可以正常播放。

**Comment by qdsfdhvh** [comment]
```swift
videoMedia.addOptions([
    "http-user-agent": "Bilibili Freedoooooom/MarkII",
    "http-referrer": "https://www.bilibili.com/video/av\(avId)"
])
```
我给vlc加了这些配置后能放了，不知道能不能对你有帮助；[vlc的配置参照的这里](https://wiki.videolan.org/VLC_command-line_help)。

**Comment by bemyae** [comment]
@qdsfdhvh  感谢你的回复，好久没写swift了。最近考虑更新这个项目（先把您的答案加到里面），然后简单重构一下并追加功能（播放控制，分p，历史记录，收藏夹，推荐）。

**Comment by bemyae** [comment]
新版本 参照上面的方法解决
